### ISSUE TITLE
Account actions (login/registreren/profile updaten)

### ISSUE THREAD

**Issue by Kvdekker** [bahaasala/blok-tech-team-b#3]

**Comment by Kvdekker** [comment]
Graag iemand even naar kijken, krijg constant de loginFailed is not defined
    at eval ("C:\\Users\\Koen-GamePC\\Documents\\GitHub\\blok-tech-team-b\\views\\login.ejs":12:17)
    at login (C:\Users\Koen-GamePC\Documents\GitHub\blok-tech-team-b\node_modules\ejs\lib\ejs.js:703:17)
    at tryHandleCache (C:\Users\Koen-GamePC\Documents\GitHub\blok-tech-team-b\node_modules\ejs\lib\ejs.js:274:36)
    at exports.renderFile [as engine] (C:\Users\Koen-GamePC\Documents\GitHub\blok-tech-team-b\node_modules\ejs\lib\ejs.js:491:10)
    at View.render (C:\Users\Koen-GamePC\Documents\GitHub\blok-tech-team-b\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\Koen-GamePC\Documents\GitHub\blok-tech-team-b\node_modules\express\lib\application.js:657:10)
    at Function.render (C:\Users\Koen-GamePC\Documents\GitHub\blok-tech-team-b\node_modules\express\lib\application.js:609:3)
    at ServerResponse.render (C:\Users\Koen-GamePC\Documents\GitHub\blok-tech-team-b\node_modules\express\lib\response.js:1039:7)
    at res.render (C:\Users\Koen-GamePC\Documents\GitHub\blok-tech-team-b\node_modules\express-ejs-layouts\lib\express-layouts.js:77:18)
    at loginController (C:\Users\Koen-GamePC\Documents\GitHub\blok-tech-team-b\controllers\loginController.js:5:9) error.
